const fs = require('fs');
const path = require('path');

const targetFile = path.join('d:', 'Cupcakes', 'src', 'actions', 'material-actions.ts');
let content = fs.readFileSync(targetFile, 'utf8');

const newFunction = `export async function autoSaveMaterial(payload: { 
  id: string; 
  title: string; 
  questions?: any[]; 
  readingText?: string;
  videoUrl?: string;
  audioUrl?: string;
  subject?: string;
  gradeLevel?: string;
  shortDescription?: string;
  tags?: string;
  instructions?: string;
  categoryIds?: string[];
  targetAudiences?: string[];
  thumbnail?: string | null;
  ttsVoice?: string;
  ttsSpeed?: number;
  audioMetadata?: any;
}) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  if (!payload.id) throw new Error('Missing ID');

  const isDemoId = payload.id === 'clp_reading_001';

  // 1. Parallelize Initial Reads
  const [existing, currentQuestions] = await Promise.all([
    prisma.assignment.findUnique({ where: { id: payload.id }, include: { lesson: true } }),
    payload.questions && Array.isArray(payload.questions) 
      ? prisma.question.findMany({ where: { assignmentId: payload.id } }) 
      : Promise.resolve([])
  ]);
  
  if (!isDemoId && (!existing || existing.teacherId !== session.user.id)) {
    throw new Error('Forbidden: You do not have permission to edit this material.');
  }

  // Handle thumbnail
  let thumbnail = payload.thumbnail !== undefined ? payload.thumbnail : existing?.thumbnail;
  const isAutoGenerated = !thumbnail || (typeof thumbnail === 'string' && thumbnail.includes('api.dicebear.com'));
  if (isAutoGenerated && !payload.thumbnail) {
    thumbnail = await generateMaterialThumbnail(
      { title: payload.title, subject: payload.subject || existing?.subject || 'English' },
      payload.questions || []
    );
  }

  console.log(\`[AutoSave] Starting update for assignment: \${payload.id}\`);

  const updatePayload: any = { 
    updatedAt: new Date(),
    ...(payload.targetAudiences !== undefined && { targetAudiences: { set: payload.targetAudiences } }),
    ...(payload.categoryIds !== undefined && { categories: { set: payload.categoryIds.map((id: string) => ({ id })) } })
  };

  if (existing) {
    const fields = ['title', 'readingText', 'videoUrl', 'audioUrl', 'ttsVoice', 'ttsSpeed', 'subject', 'gradeLevel', 'shortDescription', 'tags', 'instructions', 'audioMetadata'];
    for (const field of fields) {
      if (payload[field as keyof typeof payload] !== undefined && payload[field as keyof typeof payload] !== existing[field as keyof typeof existing]) {
        updatePayload[field] = payload[field as keyof typeof payload] || null;
      }
    }
    if (thumbnail !== undefined && thumbnail !== existing.thumbnail) updatePayload.thumbnail = thumbnail;
  } else {
    updatePayload.title = payload.title;
    updatePayload.thumbnail = thumbnail;
    updatePayload.readingText = payload.readingText || null;
    updatePayload.videoUrl = payload.videoUrl || null;
    updatePayload.audioUrl = payload.audioUrl || null;
    updatePayload.ttsVoice = payload.ttsVoice || null;
    updatePayload.ttsSpeed = payload.ttsSpeed || null;
    updatePayload.subject = payload.subject || null;
    updatePayload.gradeLevel = payload.gradeLevel || null;
    updatePayload.shortDescription = payload.shortDescription || null;
    updatePayload.tags = payload.tags || "";
    updatePayload.instructions = payload.instructions || null;
    updatePayload.audioMetadata = payload.audioMetadata || null;
  }

  const newSlug = !existing ? await generateUniqueSlug(payload.title, 'assignment') : undefined;

  const transactions: any[] = [];

  // Assignment upsert
  transactions.push(
    prisma.assignment.upsert({
      where: { id: payload.id },
      update: updatePayload,
      create: {
        id: payload.id,
        title: payload.title,
        slug: newSlug,
        thumbnail,
        readingText: payload.readingText || null,
        videoUrl: payload.videoUrl || null,
        audioUrl: payload.audioUrl || null,
        ttsVoice: payload.ttsVoice || null,
        ttsSpeed: payload.ttsSpeed || null,
        audioMetadata: payload.audioMetadata || null,
        subject: payload.subject || null,
        gradeLevel: payload.gradeLevel || null,
        shortDescription: payload.shortDescription || null,
        tags: payload.tags || "",
        instructions: payload.instructions || null,
        teacherId: session.user.id,
        materialType: 'READING', 
        status: 'DRAFT',
        targetAudiences: payload.targetAudiences !== undefined ? payload.targetAudiences : [],
        categories: {
          connect: payload.categoryIds ? payload.categoryIds.map(id => ({ id })) : []
        }
      }
    })
  );

  // Sync to Lesson if exists
  if (existing && existing.lesson) {
    const lessonUpdateData: any = {
      title: payload.title,
    };
    if (payload.shortDescription !== undefined) lessonUpdateData.description = payload.shortDescription || null;
    if (payload.videoUrl !== undefined) lessonUpdateData.videoUrl = payload.videoUrl || null;
    if (payload.audioUrl !== undefined) lessonUpdateData.audioUrl = payload.audioUrl || null;
    if (payload.audioMetadata !== undefined) lessonUpdateData.audioMetadata = payload.audioMetadata || null;
    if (thumbnail !== undefined) lessonUpdateData.thumbnail = thumbnail || null;
    if (payload.targetAudiences !== undefined) lessonUpdateData.targetAudiences = { set: payload.targetAudiences };
    if (payload.categoryIds !== undefined) lessonUpdateData.categories = { set: payload.categoryIds.map(id => ({ id })) };

    transactions.push(
      prisma.lesson.update({
        where: { id: existing.lesson.id },
        data: lessonUpdateData
      })
    );
  }

  let toCreateCount = 0;
  let toUpdateCount = 0;

  // Differential update for questions
  if (payload.questions && Array.isArray(payload.questions)) {
    const currentIds = currentQuestions.map((q: any) => q.id);
    const payloadIds = payload.questions.map(q => q.id).filter(Boolean);

    const idsToDelete = currentIds.filter(id => !payloadIds.includes(id));
    if (idsToDelete.length > 0) {
      transactions.push(
        prisma.question.deleteMany({
          where: { id: { in: idsToDelete } }
        })
      );
    }

    const toCreate: any[] = [];
    
    for (let idx = 0; idx < payload.questions.length; idx++) {
      const q = payload.questions[idx];
      const isExisting = q.id && currentIds.includes(q.id);

      const questionData = {
        assignmentId: payload.id,
        type: q.type,
        orderIndex: idx,
        points: Number(q.points) || 1.0,
        explanation: q.explanation || null,
        content: typeof q.content === 'object' ? JSON.stringify(q.content) : q.content || "{}",
        mediaType: q.mediaType || 'NONE',
        mediaUrl: q.mediaUrl || null,
        imageUrl: q.imageUrl || null,
        audioUrl: q.audioUrl || null,
        videoUrl: q.videoUrl || null,
        isBanked: q.isBanked !== undefined ? q.isBanked : (q.isAiGenerated ? false : true),
        isAiGenerated: q.isAiGenerated || false,
        originalId: q.originalId || null
      };

      if (isExisting) {
        const currentQ = currentQuestions.find((cq: any) => cq.id === q.id);
        let changed = false;
        const uData: any = {};
        
        if (currentQ) {
          for (const key of Object.keys(questionData)) {
            let isDifferent = false;
            if (key === 'content') {
              try {
                const currentContentObj = typeof currentQ.content === 'string' ? JSON.parse(currentQ.content || "{}") : currentQ.content;
                const newContentObj = typeof questionData.content === 'string' ? JSON.parse(questionData.content || "{}") : questionData.content;
                isDifferent = !deepEqual(currentContentObj, newContentObj);
              } catch(e) {
                isDifferent = currentQ.content !== questionData.content;
              }
            } else {
              isDifferent = (currentQ as any)[key] !== (questionData as any)[key];
            }
            
            if (isDifferent) {
              uData[key] = (questionData as any)[key];
              changed = true;
            }
          }
        }
        
        if (changed) {
          toUpdateCount++;
          transactions.push(
            prisma.question.update({
              where: { id: q.id },
              data: uData
            })
          );
        }
      } else {
        toCreate.push({ ...questionData, id: q.id });
      }
    }
    
    if (toCreate.length > 0) {
      const uniqueToCreate = Array.from(new Map(toCreate.map(item => [item.id, item])).values());
      toCreateCount = uniqueToCreate.length;
      transactions.push(
        prisma.question.createMany({
          data: uniqueToCreate,
          skipDuplicates: true
        })
      );
    }
  }

  // 4. Execute all transactions in one round trip!
  await prisma.$transaction(transactions);

  console.log(\`[AutoSave] Upserted questions: \${toCreateCount} created, \${toUpdateCount} updated for \${payload.id}\`);

  // Sync to Homepage Feed
  after(() => {
    syncToHomepageFeed(payload.id, "EXERCISE").catch(err => {
      console.error("[AutoSave] Background sync feed failed:", err);
    });
    
    if (existing && existing.lesson) {
      syncToHomepageFeed(existing.lesson.id, "LESSON").catch(err => {
        console.error("[AutoSave] Background sync feed failed for lesson:", err);
      });
    }
  });

  return { success: true, savedAt: new Date() };
}`;

const startIndex = content.indexOf('export async function autoSaveMaterial(');
if (startIndex === -1) throw new Error('Not found autoSaveMaterial');

// Find the end of the function. We will match the string: "return { success: true, savedAt: new Date() };\n}"
// We can use a regex to find the closing brace.
const searchStr = 'return { success: true, savedAt: new Date() };\n}';
const searchStrAlt = 'return { success: true, savedAt: new Date() };\r\n}';

let endIndex = content.indexOf(searchStr, startIndex);
let endLength = searchStr.length;
if (endIndex === -1) {
  endIndex = content.indexOf(searchStrAlt, startIndex);
  endLength = searchStrAlt.length;
}

if (endIndex === -1) throw new Error('Not found end of autoSaveMaterial');

const newContent = content.substring(0, startIndex) + newFunction + content.substring(endIndex + endLength);

fs.writeFileSync(targetFile, newContent);
console.log('Successfully replaced autoSaveMaterial!');
