"use server"

import { auth } from '@/auth';
import prisma from '@/lib/prisma';
import { revalidatePath } from 'next/cache';
import crypto from 'crypto';
import { MaterialStatus } from '@prisma/client';

function generateMaterialThumbnail(assignment: { title: string; subject: string | null }, questions: any[]) {
  // Analyze content to create a stable seed
  let contentText = assignment.title;
  questions.forEach(q => {
    // Basic extraction from common question structures
    const c = typeof q.content === 'object' ? q.content : (typeof q.content === 'string' ? JSON.parse(q.content) : q);
    
    // Extract text based on question structure
    const textElements = [
      c.questionText, 
      c.statement, 
      c.instruction, 
      c.textWithBlanks,
      q.explanation
    ];
    
    contentText += textElements.filter(Boolean).join('');
    
    // Add options/items for more uniqueness
    if (c.options) c.options.forEach((o: any) => contentText += (o.text || ''));
    if (c.pairs) c.pairs.forEach((p: any) => contentText += (p.rightText || ''));
    if (c.items) c.items.forEach((i: any) => contentText += (i.text || ''));
  });

  const hash = crypto.createHash('sha256').update(contentText).digest('hex');
  
  // Reasonable coloring based on subject
  let rowColor = '2563eb'; // Default Blue
  const subject = assignment.subject || '';
  if (subject.includes('Toán')) rowColor = '3b82f6';
  else if (subject.includes('Anh')) rowColor = '6366f1';
  else if (subject.includes('Văn')) rowColor = 'f97316';
  else if (subject.includes('Khoa học')) rowColor = '14b8a6';
  else if (subject.includes('Lịch sử')) rowColor = 'ef4444';
  
  // Return DiceBear Identicon URL
  return `https://api.dicebear.com/7.x/identicon/svg?seed=${hash}&backgroundColor=f0f2f4&rowColor=${rowColor}`;
}

export async function createDraftMaterial(type: 'EXERCISE' | 'READING' | 'FLASHCARD') {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const newAss = await prisma.assignment.create({
    data: {
      title: 'Bài tập mới',
      materialType: type,
      teacherId: session.user.id,
      status: 'DRAFT'
    }
  });

  return newAss.id;
}

export async function autoSaveMaterial(payload: { id: string; title: string; type: string; questions: any[] }) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  if (!payload.id) throw new Error('Missing ID');

  // Verify ownership to prevent IDOR
  const existing = await prisma.assignment.findUnique({ where: { id: payload.id }});
  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden: You do not have permission to edit this material.');
  }

  // MVP Rule #3: Lock assignment if there are submissions
  const submissionCount = await prisma.submission.count({
    where: { assignmentId: payload.id }
  });
  
  if (submissionCount > 0) {
    throw new Error('Locked: Không thể sửa bài tập khi đã có học sinh nộp bài.');
  }

  // Update via transaction
  await prisma.$transaction(async (tx) => {
    // Generate thumbnail if not manually set
    // For now, we always regenerate it if the content changes, unless it's a non-identicon URL
    let thumbnail = existing.thumbnail;
    const isAutoGenerated = !thumbnail || thumbnail.includes('api.dicebear.com');
    
    if (isAutoGenerated) {
      thumbnail = generateMaterialThumbnail(
        { title: payload.title, subject: existing.subject },
        payload.questions
      );
    }

    // Update main info
    await tx.assignment.update({
      where: { id: payload.id },
      data: { 
        title: payload.title,
        thumbnail,
        updatedAt: new Date(),
      }
    });

    // Wipe old questions and insert new ones to handle reordering/deletions robustly
    await tx.question.deleteMany({
      where: { assignmentId: payload.id }
    });

    if (payload.questions && payload.questions.length > 0) {
      await tx.question.createMany({
        data: payload.questions.map((q: any, idx: number) => ({
          assignmentId: payload.id,
          type: q.type,
          orderIndex: idx,
          points: Number(q.points) || 1.0,
          explanation: q.explanation || null,
          content: JSON.stringify(q),
          mediaType: q.mediaType || 'NONE',
          mediaUrl: q.mediaUrl || null,
          imageUrl: q.imageUrl || null,
          audioUrl: q.audioUrl || null,
          videoUrl: q.videoUrl || null
        }))
      });
    }
  });

  return { success: true, savedAt: new Date() };
}

export async function getMyAssignments() {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const assignments = await prisma.assignment.findMany({
    where: { teacherId: session.user.id, deletedAt: null },
    include: {
      _count: {
        select: { questions: true }
      }
    },
    orderBy: { createdAt: 'desc' }
  });

  return assignments;
}

export async function syncAssignmentClasses(assignmentId: string, payload: any) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const { classIds, startDate, deadline, timeLimit, maxAttempts, focusMode, allowLateSubmission } = payload;

  // Verify ownership of assignment
  const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }});
  if (!assignment || assignment.teacherId !== session.user.id) {
    throw new Error('Forbidden: You do not own this assignment.');
  }

  // Verify status: Draft cannot be assigned
  if (assignment.status === 'DRAFT' && classIds.length > 0) {
    throw new Error('Không thể giao bài tập đang ở trạng thái Bản nháp. Vui lòng chuyển bài tập sang trạng thái Riêng tư hoặc Công khai để giao bài.');
  }

  await prisma.$transaction(async (tx) => {
    // 1. Remove classes no longer in the list
    await tx.assignmentClass.deleteMany({
      where: {
        assignmentId,
        classId: { notIn: classIds }
      }
    });

    // 2. Add or update classes in the list
    if (classIds.length > 0) {
      for (const cid of classIds) {
        await tx.assignmentClass.upsert({
          where: {
            assignmentId_classId: { assignmentId, classId: cid }
          },
          update: { 
            assignedAt: new Date(),
            startDate: startDate ? new Date(startDate) : null,
            dueDate: deadline ? new Date(deadline) : null,
            timeLimit: timeLimit ? Number(timeLimit) : null,
            maxAttempts: maxAttempts ? Number(maxAttempts) : 1,
            focusMode: !!focusMode,
            allowLateSubmission: !!allowLateSubmission
          },
          create: { 
            assignmentId, 
            classId: cid,
            startDate: startDate ? new Date(startDate) : null,
            dueDate: deadline ? new Date(deadline) : null,
            timeLimit: timeLimit ? Number(timeLimit) : null,
            maxAttempts: maxAttempts ? Number(maxAttempts) : 1,
            focusMode: !!focusMode,
            allowLateSubmission: !!allowLateSubmission
          }
        });
      }
    }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function unassignMaterialFromClass(assignmentId: string, classId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  // Verify ownership
  const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }});
  if (!assignment || assignment.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  await prisma.assignmentClass.delete({
    where: {
      assignmentId_classId: { assignmentId, classId }
    }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function getTeacherClasses() {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const classes = await prisma.class.findMany({
    where: { teacherId: session.user.id, deletedAt: null },
    include: {
      _count: {
        select: { enrollments: true }
      }
    },
    orderBy: { name: 'asc' }
  });

  return classes.map(c => ({
    id: c.id,
    name: c.name,
    studentCount: c._count.enrollments
  }));
}

export async function deleteMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const existing = await prisma.assignment.findUnique({ 
    where: { id },
    include: { _count: { select: { targetClasses: true } } }
  });

  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden: You do not have permission to delete this material.');
  }

  await prisma.assignment.update({
    where: { id },
    data: { deletedAt: new Date() }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/materials/trash');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function duplicateMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const source = await prisma.assignment.findUnique({
    where: { id, deletedAt: null },
    include: { 
      questions: true,
      flashcardDeck: { include: { cards: true } }
    }
  });

  if (!source || source.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  const newAss = await prisma.assignment.create({
    data: {
      title: `${source.title} (Bản sao)`,
      status: 'DRAFT',
      materialType: source.materialType,
      teacherId: session.user.id,
      defaultPoints: source.defaultPoints,
      coefficient: source.coefficient,
      allowLateSubmission: source.allowLateSubmission,
      timeLimit: source.timeLimit,
      themeColor: source.themeColor,
      subject: source.subject,
      gradeLevel: source.gradeLevel,
      thumbnail: generateMaterialThumbnail(
        { title: `${source.title} (Bản sao)`, subject: source.subject },
        source.questions
      ),
      questions: {
        create: source.questions.map(q => ({
          type: q.type,
          orderIndex: q.orderIndex,
          points: q.points,
          explanation: q.explanation,
          content: q.content,
          mediaType: q.mediaType,
          mediaUrl: q.mediaUrl,
          imageUrl: q.imageUrl,
          audioUrl: q.audioUrl,
        }))
      },
      flashcardDeck: source.flashcardDeck ? {
        create: {
          cards: {
            create: source.flashcardDeck.cards.map(c => ({
              frontText: c.frontText,
              backText: c.backText,
              imageUrl: c.imageUrl,
              orderIndex: c.orderIndex
            }))
          }
        }
      } : undefined
    }
  });

  revalidatePath('/teacher/materials');
  return newAss.id;
}

export async function restoreMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const existing = await prisma.assignment.findUnique({ where: { id }});
  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  await prisma.assignment.update({
    where: { id },
    data: { deletedAt: null }
  });

  revalidatePath('/teacher/materials/trash');
  revalidatePath('/teacher/materials');
  return { success: true };
}

export async function permanentlyDeleteMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const existing = await prisma.assignment.findUnique({ 
    where: { id },
    include: { _count: { select: { targetClasses: true } } }
  });

  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  // Still check if it was assigned (sanity check)
  if (existing._count.targetClasses > 0) {
    throw new Error('Không thể xóa vĩnh viễn bài tập đã được giao.');
  }

  await prisma.assignment.delete({
    where: { id }
  });

  revalidatePath('/teacher/materials/trash');
  return { success: true };
}

export async function updateMaterialStatus(id: string, status: MaterialStatus) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const existing = await prisma.assignment.findUnique({ where: { id }});
  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  // If changing from DRAFT to something else, check if there's at least 1 question
  if (existing.status === 'DRAFT' && status !== 'DRAFT') {
    const questionCount = await prisma.question.count({ where: { assignmentId: id } });
    if (questionCount === 0) {
      throw new Error('Bài tập phải có ít nhất 1 câu hỏi mới có thể đổi trạng thái.');
    }
  }

  // If changing TO draft, check if it's already assigned
  if (status === 'DRAFT') {
    const assignedCount = await prisma.assignmentClass.count({ where: { assignmentId: id } });
    if (assignedCount > 0) {
      throw new Error('Bài tập đã được giao cho lớp học không thể chuyển lại thành Bản nháp.');
    }
  }

  await prisma.assignment.update({
    where: { id },
    data: { status }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}
