"use server"

import { auth } from '@/auth';
import prisma from '@/lib/prisma';
import { revalidatePath } from 'next/cache';
import crypto from 'crypto';
import { MaterialStatus } from '@/generated/client';

export async function generateMaterialThumbnail(assignment: { title: string; subject: string | null }, questions: any[]) {
  // Analyze content to create a stable seed
  let contentText = assignment.title;
  questions.forEach(q => {
    // Basic extraction from common question structures
    const c = typeof q.content === 'object' ? q.content : (typeof q.content === 'string' ? JSON.parse(q.content) : q);
    
    // Extract text based on question structure
    const textElements = [
      c?.questionText, 
      c?.statement, 
      c?.instruction, 
      c?.textWithBlanks,
      q?.explanation
    ];
    
    contentText += textElements.filter(Boolean).join('');
    
    // Add options/items for more uniqueness with safety checks
    if (Array.isArray(c?.options)) c.options.forEach((o: any) => contentText += (o?.text || ''));
    if (Array.isArray(c?.pairs)) c.pairs.forEach((p: any) => contentText += (p?.rightText || ''));
    if (Array.isArray(c?.items)) c.items.forEach((i: any) => contentText += (i?.text || ''));
  });

  const hash = crypto.createHash('sha256').update(contentText || 'default-seed').digest('hex');
  
  // Reasonable coloring based on subject
  let rowColor = '2563eb'; // Default Blue
  const subject = assignment.subject || '';
  if (subject.includes('Toán')) rowColor = '3b82f6';
  else if (subject.includes('Anh')) rowColor = '6366f1';
  else if (subject.includes('Văn')) rowColor = 'f97316';
  else if (subject.includes('Khoa học')) rowColor = '14b8a6';
  else if (subject.includes('Lịch sử')) rowColor = 'ef4444';
  
  // Return DiceBear Identicon URL
  return `https://api.dicebear.com/7.x/identicon/svg?seed=${hash}&backgroundColor=f0f2f4&rowColor=${rowColor}`;
}

export async function createDraftMaterial(type: 'EXERCISE' | 'READING' | 'FLASHCARD') {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const newAss = await prisma.assignment.create({
    data: {
      title: 'Bài tập mới',
      materialType: type,
      teacherId: session.user.id,
      status: 'DRAFT'
    }
  });

  return newAss.id;
}

export async function createDraftLesson() {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  // Create Assignment first because Lesson depends on it
  const newAssignment = await prisma.assignment.create({
    data: {
      title: 'Bài học mới',
      materialType: 'READING', // Default for lessons
      status: 'DRAFT',
      teacherId: session.user.id,
    }
  });

  await prisma.lesson.create({
    data: {
      title: 'Bài học mới',
      teacherId: session.user.id,
      assignmentId: newAssignment.id
    }
  });

  return newAssignment.id; // Return assignment ID for the editor
}

export async function autoSaveMaterial(payload: { 
  id: string; 
  title: string; 
  type: string; 
  questions: any[]; 
  readingText?: string;
  videoUrl?: string;
  audioUrl?: string;
  subject?: string;
  gradeLevel?: string;
  shortDescription?: string;
  tags?: string;
  instructions?: string;
  categoryIds?: string[];
}) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  if (!payload.id) throw new Error('Missing ID');

  // Verify ownership to prevent IDOR
  const existing = await prisma.assignment.findUnique({ where: { id: payload.id }});
  
  // For demo assignment ID, we skip strict ownership check to allow test users to edit
  const isDemoId = payload.id === 'clp_reading_001';
  
  if (!isDemoId && (!existing || existing.teacherId !== session.user.id)) {
    throw new Error('Forbidden: You do not have permission to edit this material.');
  }

  // Update via transaction
  await prisma.$transaction(async (tx) => {
    // Generate thumbnail if not manually set
    let thumbnail = existing?.thumbnail;
    const isAutoGenerated = !thumbnail || thumbnail.includes('api.dicebear.com');
    
    if (isAutoGenerated) {
      thumbnail = await generateMaterialThumbnail(
        { title: payload.title, subject: payload.subject || existing?.subject || 'English' },
        payload.questions
      );
    }

    console.log(`[AutoSave] Starting update for assignment: ${payload.id}`);

    // Update main info (using upsert)
    await tx.assignment.upsert({
      where: { id: payload.id },
      update: { 
        title: payload.title,
        thumbnail,
        readingText: payload.readingText || null,
        videoUrl: payload.videoUrl || null,
        audioUrl: payload.audioUrl || null,
        subject: payload.subject || null,
        gradeLevel: payload.gradeLevel || null,
        shortDescription: payload.shortDescription || null,
        tags: payload.tags || "",
        instructions: payload.instructions || null,
        updatedAt: new Date(),
        categories: {
          set: payload.categoryIds ? payload.categoryIds.map(id => ({ id })) : []
        }
      },
      create: {
        id: payload.id,
        title: payload.title,
        thumbnail,
        readingText: payload.readingText || null,
        videoUrl: payload.videoUrl || null,
        audioUrl: payload.audioUrl || null,
        subject: payload.subject || null,
        gradeLevel: payload.gradeLevel || null,
        shortDescription: payload.shortDescription || null,
        tags: payload.tags || "",
        instructions: payload.instructions || null,
        teacherId: session.user.id,
        materialType: (payload.type as any) || 'READING',
        status: 'DRAFT',
        categories: {
          connect: payload.categoryIds ? payload.categoryIds.map(id => ({ id })) : []
        }
      }
    });

    // Wipe old questions
    const deleteResult = await tx.question.deleteMany({
      where: { assignmentId: payload.id }
    });
    console.log(`[AutoSave] Deleted ${deleteResult.count} old questions for ${payload.id}`);

    if (payload.questions && Array.isArray(payload.questions)) {
      // Use createMany for high performance and to prevent transaction timeouts
      const questionsData = payload.questions.map((q, idx) => ({
        assignmentId: payload.id,
        type: q.type,
        orderIndex: idx,
        points: Number(q.points) || 1.0,
        explanation: q.explanation || null,
        content: JSON.stringify(q.content || {}),
        mediaType: q.mediaType || 'NONE',
        mediaUrl: q.mediaUrl || null,
        imageUrl: q.imageUrl || null,
        audioUrl: q.audioUrl || null,
        videoUrl: q.videoUrl || null,
        isBanked: q.isBanked !== undefined ? q.isBanked : true,
        isAiGenerated: q.isAiGenerated || false,
        originalId: q.originalId || null
      }));

      await tx.question.createMany({
        data: questionsData
      });
      
      console.log(`[AutoSave] Created ${payload.questions.length} new questions for ${payload.id}`);
    }
  }, {
    timeout: 30000 // Increase timeout to 30 seconds for stability
  });

  return { success: true, savedAt: new Date() };
}

export async function getMyAssignments() {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const assignments = await prisma.assignment.findMany({
    where: { teacherId: session.user.id, deletedAt: null },
    include: {
      _count: {
        select: { questions: true }
      }
    },
    orderBy: { createdAt: 'desc' }
  });

  return assignments;
}

export async function syncAssignmentClasses(assignmentId: string, payload: any) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const { classIds, startDate, deadline, timeLimit, maxAttempts, focusMode, allowLateSubmission } = payload;

  // Verify ownership of assignment
  const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }});
  if (!assignment || assignment.teacherId !== session.user.id) {
    throw new Error('Forbidden: You do not own this assignment.');
  }

  // Verify status: Draft cannot be assigned
  if (assignment.status === 'DRAFT' && classIds.length > 0) {
    throw new Error('Không thể giao bài tập đang ở trạng thái Bản nháp. Vui lòng chuyển bài tập sang trạng thái Riêng tư hoặc Công khai để giao bài.');
  }

  await prisma.$transaction(async (tx) => {
    // 1. Remove classes no longer in the list
    await tx.assignmentClass.deleteMany({
      where: {
        assignmentId,
        classId: { notIn: classIds }
      }
    });

    // 2. Add or update classes in the list
    if (classIds.length > 0) {
      for (const cid of classIds) {
        const isNewAssignment = await tx.assignmentClass.findUnique({
          where: { assignmentId_classId: { assignmentId, classId: cid } }
        }) === null;

        await tx.assignmentClass.upsert({
          where: {
            assignmentId_classId: { assignmentId, classId: cid }
          },
          update: { 
            assignedAt: new Date(),
            startDate: startDate ? new Date(startDate) : null,
            dueDate: deadline ? new Date(deadline) : null,
            timeLimit: timeLimit ? Number(timeLimit) : null,
            maxAttempts: maxAttempts ? Number(maxAttempts) : 1,
            focusMode: !!focusMode,
            allowLateSubmission: !!allowLateSubmission
          },
          create: { 
            assignmentId, 
            classId: cid,
            startDate: startDate ? new Date(startDate) : null,
            dueDate: deadline ? new Date(deadline) : null,
            timeLimit: timeLimit ? Number(timeLimit) : null,
            maxAttempts: maxAttempts ? Number(maxAttempts) : 1,
            focusMode: !!focusMode,
            allowLateSubmission: !!allowLateSubmission
          }
        });

        if (isNewAssignment) {
          // Notify students
          const students = await tx.classEnrollment.findMany({
            where: { classId: cid, status: 'ACTIVE' },
            select: { studentId: true }
          });

          const { createNotification } = await import('@/actions/notification-actions');
          for (const student of students) {
            await createNotification(
              student.studentId,
              'NEW_ASSIGNMENT',
              'Bài tập mới được giao',
              `${session.user.name || 'Giáo viên'} vừa giao bài tập mới: "${assignment.title}"`,
              `/student/assignments/${assignmentId}/run`
            );
          }
        }
      }
    }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function unassignMaterialFromClass(assignmentId: string, classId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  // Verify ownership
  const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }});
  if (!assignment || assignment.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  await prisma.assignmentClass.delete({
    where: {
      assignmentId_classId: { assignmentId, classId }
    }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function getTeacherClasses() {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const classes = await prisma.class.findMany({
    where: { teacherId: session.user.id, deletedAt: null },
    include: {
      _count: {
        select: { enrollments: true }
      }
    },
    orderBy: { name: 'asc' }
  });

  return classes.map(c => ({
    id: c.id,
    name: c.name,
    studentCount: c._count.enrollments
  }));
}

export async function deleteMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  // Try finding as assignment
  const assignment = await prisma.assignment.findUnique({ 
    where: { id },
    include: { lesson: true, _count: { select: { targetClasses: true } } }
  });

  if (assignment) {
    if (assignment.teacherId !== session.user.id) throw new Error('Forbidden');
    
    await prisma.$transaction([
      prisma.assignment.update({
        where: { id },
        data: { deletedAt: new Date() }
      }),
      ...(assignment.lesson ? [
        prisma.lesson.update({
          where: { id: assignment.lesson.id },
          data: { deletedAt: new Date() }
        })
      ] : [])
    ]);
  } else {
    // Try finding as lesson
    const lesson = await prisma.lesson.findUnique({
      where: { id },
      include: { assignment: true }
    });

    if (!lesson || lesson.teacherId !== session.user.id) {
      throw new Error('Forbidden: You do not have permission to delete this material.');
    }

    await prisma.$transaction([
      prisma.lesson.update({
        where: { id },
        data: { deletedAt: new Date() }
      }),
      ...(lesson.assignment ? [
        prisma.assignment.update({
          where: { id: lesson.assignment.id },
          data: { deletedAt: new Date() }
        })
      ] : [])
    ]);
  }

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/materials/trash');
  revalidatePath('/teacher/lessons');
  revalidatePath('/teacher/dashboard');
  return { success: true };
}

export async function duplicateMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const source = await prisma.assignment.findUnique({
    where: { id, deletedAt: null },
    include: { 
      questions: true,
      flashcardDeck: { include: { cards: true } }
    }
  });

  if (!source || source.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  const newAss = await prisma.assignment.create({
    data: {
      title: `${source.title} (Bản sao)`,
      status: 'DRAFT',
      materialType: source.materialType,
      teacherId: session.user.id,
      defaultPoints: source.defaultPoints,
      coefficient: source.coefficient,
      allowLateSubmission: source.allowLateSubmission,
      timeLimit: source.timeLimit,
      themeColor: source.themeColor,
      subject: source.subject,
      gradeLevel: source.gradeLevel,
      shortDescription: source.shortDescription,
      tags: source.tags,
      instructions: source.instructions,
      readingText: source.readingText,
      videoUrl: (source as any).videoUrl || null,
      audioUrl: (source as any).audioUrl || null,
      thumbnail: await generateMaterialThumbnail(
        { title: `${source.title} (Bản sao)`, subject: source.subject },
        source.questions
      ),
      questions: {
        create: source.questions.map(q => ({
          type: q.type,
          orderIndex: q.orderIndex,
          points: q.points,
          explanation: q.explanation,
          content: q.content,
          mediaType: q.mediaType,
          mediaUrl: q.mediaUrl,
          imageUrl: q.imageUrl,
          audioUrl: q.audioUrl,
        }))
      },
      flashcardDeck: source.flashcardDeck ? {
        create: {
          cards: {
            create: source.flashcardDeck.cards.map(c => ({
              frontText: c.frontText,
              backText: c.backText,
              imageUrl: c.imageUrl,
              orderIndex: c.orderIndex
            }))
          }
        }
      } : undefined
    }
  });

  revalidatePath('/teacher/materials');
  return newAss.id;
}

export async function restoreMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const assignment = await prisma.assignment.findUnique({ 
    where: { id },
    include: { lesson: true }
  });

  if (assignment) {
    if (assignment.teacherId !== session.user.id) throw new Error('Forbidden');
    await prisma.$transaction([
      prisma.assignment.update({ where: { id }, data: { deletedAt: null } }),
      ...(assignment.lesson ? [prisma.lesson.update({ where: { id: assignment.lesson.id }, data: { deletedAt: null } })] : [])
    ]);
  } else {
    const lesson = await prisma.lesson.findUnique({ 
      where: { id },
      include: { assignment: true }
    });
    if (!lesson || lesson.teacherId !== session.user.id) throw new Error('Forbidden');
    await prisma.$transaction([
      prisma.lesson.update({ where: { id }, data: { deletedAt: null } }),
      ...(lesson.assignment ? [prisma.assignment.update({ where: { id: lesson.assignment.id }, data: { deletedAt: null } })] : [])
    ]);
  }

  revalidatePath('/teacher/materials/trash');
  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/lessons');
  return { success: true };
}

export async function permanentlyDeleteMaterial(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const assignment = await prisma.assignment.findUnique({ 
    where: { id },
    include: { lesson: true, _count: { select: { targetClasses: true } } }
  });

  if (assignment) {
    if (assignment.teacherId !== session.user.id) throw new Error('Forbidden');
    if (assignment._count.targetClasses > 0) {
      throw new Error('Không thể xóa vĩnh viễn bài tập đã được giao.');
    }
    
    await prisma.$transaction([
      ...(assignment.lesson ? [prisma.lesson.delete({ where: { id: assignment.lesson.id } })] : []),
      prisma.assignment.delete({ where: { id } })
    ]);
  } else {
    const lesson = await prisma.lesson.findUnique({ 
      where: { id },
      include: { assignment: true }
    });
    if (!lesson || lesson.teacherId !== session.user.id) throw new Error('Forbidden');
    
    // If lesson has assignment, check if that assignment is assigned
    if (lesson.assignment) {
      const assCount = await prisma.assignmentClass.count({ where: { assignmentId: lesson.assignment.id } });
      if (assCount > 0) throw new Error('Không thể xóa vĩnh viễn bài học có bài tập đã được giao.');
    }

    await prisma.$transaction([
      ...(lesson.assignment ? [prisma.assignment.delete({ where: { id: lesson.assignment.id } })] : []),
      prisma.lesson.delete({ where: { id } })
    ]);
  }

  revalidatePath('/teacher/materials/trash');
  revalidatePath('/teacher/lessons');
  return { success: true };
}

export async function bulkDeleteMaterials(ids: string[]) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');
  await Promise.all(ids.map(id => deleteMaterial(id)));
  return { success: true };
}

export async function bulkRestoreMaterials(ids: string[]) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');
  await Promise.all(ids.map(id => restoreMaterial(id)));
  return { success: true };
}

export async function bulkPermanentlyDeleteMaterials(ids: string[]) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');
  await Promise.all(ids.map(id => permanentlyDeleteMaterial(id)));
  return { success: true };
}

/**
 * USE CASE: Update Material Status
 * Transitions the material between DRAFT, PRIVATE, and PUBLIC.
 * Includes business rule validation for each state.
 */
export async function updateMaterialStatus(id: string, newStatus: MaterialStatus) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const existing = await prisma.assignment.findUnique({ 
    where: { id },
    include: { _count: { select: { targetClasses: true } } }
  });

  if (!existing || existing.teacherId !== session.user.id) {
    throw new Error('Forbidden: You do not have permission to update this material.');
  }

  // 1. Validation for transitioning OUT of DRAFT
  // Materials must meet quality standards before being Private or Public
  if (existing.status === 'DRAFT' && newStatus !== 'DRAFT') {
    if (!existing.title || existing.title.trim() === '') {
      throw new Error('Bài tập phải có Tiêu đề trước khi đổi trạng thái.');
    }

    // Check content sufficiency (Reading materials)
    if (existing.materialType === 'READING') {
      const cleanContent = (existing.readingText || '').replace('Bôi đen từ mới để thiết lập vocabulary chi tiết.', '').trim();
      if (!cleanContent || (cleanContent.length < 50 && !(existing.readingText || '').includes('<img'))) {
        throw new Error('Nội dung bài đọc chưa đạt yêu cầu (tối thiểu 50 ký tự hoặc có hình ảnh minh họa).');
      }
    }
    
    // Check question count (Exercises)
    if (existing.materialType === 'EXERCISE') {
      const questionCount = await prisma.question.count({ where: { assignmentId: id } });
      if (questionCount === 0) {
        throw new Error('Bài tập trắc nghiệm phải có ít nhất một câu hỏi.');
      }
    }

    // Check flashcard count (Flashcards)
    if (existing.materialType === 'FLASHCARD') {
      const deck = await prisma.flashcardDeck.findUnique({ 
        where: { assignmentId: id },
        include: { _count: { select: { cards: true } } }
      });
      if (!deck || deck._count.cards === 0) {
        throw new Error('Bộ thẻ ghi nhớ phải có ít nhất một thẻ bài.');
      }
    }
  }

  // 2. Validation for transitioning TO DRAFT
  // Prevents breaking existing class assignments
  if (newStatus === 'DRAFT') {
    if (existing._count.targetClasses > 0) {
      throw new Error('Bài tập đã được giao cho lớp học không thể chuyển lại thành Bản nháp. Hãy hủy giao bài trước.');
    }
  }

  // 3. Validation for PUBLIC status (Optional: stricter rules for community sharing)
  if (newStatus === 'PUBLIC') {
    // We could add more checks here, e.g., requiring at least 5 questions or a thumbnail
    if (!existing.thumbnail) {
      // Auto-generate if missing for public view
      const questions = await prisma.question.findMany({ where: { assignmentId: id } });
      const thumbnail = await generateMaterialThumbnail(
        { title: existing.title, subject: existing.subject },
        questions
      );
      await prisma.assignment.update({ where: { id }, data: { thumbnail } });
    }
  }

  await prisma.assignment.update({
    where: { id },
    data: { status: newStatus }
  });

  revalidatePath('/teacher/materials');
  revalidatePath('/teacher/dashboard');
  revalidatePath(`/teacher/materials/${id}`);
  
  return { success: true };
}

export async function assignToClass(assignmentId: string, classId: string, payload?: any) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }});
  if (!assignment || assignment.teacherId !== session.user.id) {
    throw new Error('Forbidden');
  }

  if (assignment.status === 'DRAFT') {
    throw new Error('Không thể giao bài tập đang ở trạng thái Bản nháp.');
  }

  // Update properties if passing payload
  const updateData: any = { assignedAt: new Date() };
  const createData: any = { assignmentId, classId, maxAttempts: 1 };

  if (payload) {
    if (payload.startDate) {
      updateData.startDate = new Date(payload.startDate);
      createData.startDate = new Date(payload.startDate);
    }
    if (payload.dueDate) {
      updateData.dueDate = new Date(payload.dueDate);
      createData.dueDate = new Date(payload.dueDate);
    }
    if (payload.timeLimit !== undefined) {
      updateData.timeLimit = payload.timeLimit;
      createData.timeLimit = payload.timeLimit;
    }
    if (payload.maxAttempts !== undefined) {
      updateData.maxAttempts = payload.maxAttempts;
      createData.maxAttempts = payload.maxAttempts;
    }
  }

  await prisma.assignmentClass.upsert({
    where: { assignmentId_classId: { assignmentId, classId } },
    update: updateData,
    create: createData
  });

  revalidatePath('/teacher/materials');
  revalidatePath(`/teacher/classes/${classId}`);
  return { success: true };
}
export async function saveToQuestionBank(question: any, meta: { subject?: string; gradeLevel?: string; tags?: string }) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  await prisma.questionBank.create({
    data: {
      teacherId: session.user.id,
      type: question.type,
      points: question.points,
      explanation: question.explanation,
      content: typeof question.content === 'object' ? JSON.stringify(question.content) : question.content,
      mediaType: question.mediaType,
      mediaUrl: question.mediaUrl,
      imageUrl: question.imageUrl || null,
      audioUrl: question.audioUrl || null,
      videoUrl: question.videoUrl || null,
      subject: meta.subject,
      gradeLevel: meta.gradeLevel,
      tags: meta.tags
    }
  });

  return { success: true };
}

export async function getMaterialAnalytics(assignmentId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const submissions = await prisma.submission.findMany({
    where: { assignmentId, submittedAt: { not: null } },
    include: { answers: true }
  });

  const questions = await prisma.question.findMany({
    where: { assignmentId },
    orderBy: { orderIndex: 'asc' }
  });

  const stats = questions.map(q => {
    const qAnswers = submissions.flatMap(s => s.answers.filter(a => a.questionId === q.id));
    const correctCount = qAnswers.filter(a => a.isCorrect).length;
    const totalCount = qAnswers.length;
    
    return {
      questionId: q.id,
      type: q.type,
      correctRate: totalCount > 0 ? (correctCount / totalCount) * 100 : 0,
      totalResponses: totalCount,
      isHard: totalCount > 5 && (correctCount / totalCount) < 0.3
    };
  });

  return {
    totalSubmissions: submissions.length,
    averageScore: submissions.length > 0 ? submissions.reduce((acc, s) => acc + (s.score || 0), 0) / submissions.length : 0,
    questionStats: stats
  };
}

export async function bulkAssignMaterial(assignmentId: string, payload: { classIds: string[]; startDate?: Date; deadline?: Date; timeLimit?: number }) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const { classIds, ...settings } = payload;
  
  for (const classId of classIds) {
    await assignToClass(assignmentId, classId, settings);
  }
  return { success: true };
}

export async function trackMaterialView(id: string) {
  await prisma.assignment.update({
    where: { id },
    data: { viewCount: { increment: 1 } }
  });
  return { success: true };
}

export async function getQuestionBank(searchTerm?: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');

  const questions = await prisma.questionBank.findMany({
    where: {
      teacherId: session.user.id,
      OR: searchTerm ? [
        { content: { contains: searchTerm, mode: 'insensitive' } },
        { subject: { contains: searchTerm, mode: 'insensitive' } },
        { tags: { contains: searchTerm, mode: 'insensitive' } }
      ] : undefined
    },
    orderBy: { createdAt: 'desc' }
  });

  // Parse JSON content for usage in frontend
  return questions.map(q => ({
    ...q,
    content: typeof q.content === 'string' ? JSON.parse(q.content) : q.content
  }));
}

export async function deleteFromQuestionBank(id: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');
  
  await prisma.questionBank.deleteMany({
    where: {
      id,
      teacherId: session.user.id
    }
  });
  
  return { success: true };
}

export async function updateQuestionBankTags(id: string, tags: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error('Unauthorized');
  
  await prisma.questionBank.updateMany({
    where: {
      id,
      teacherId: session.user.id
    },
    data: {
      tags
    }
  });
  
  return { success: true };
}
