"use client";

import React, { useRef } from 'react';

interface ThumbnailUploaderProps {
  value: string | null;
  onChange: (value: string | null) => void;
  label?: string;
  isUploading?: boolean;
}

export function ThumbnailUploader({ 
  value, 
  onChange, 
  label = "Ảnh thu nhỏ (16:9)",
  isUploading = false
}: ThumbnailUploaderProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const img = new Image();
        img.onload = () => {
          const canvas = document.createElement('canvas');
          let width = img.width;
          let height = img.height;
          const MAX_WIDTH = 800;
          if (width > MAX_WIDTH) {
            height = Math.round((height * MAX_WIDTH) / width);
            width = MAX_WIDTH;
          }
          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext('2d');
          ctx?.drawImage(img, 0, 0, width, height);
          const dataUrl = canvas.toDataURL('image/jpeg', 0.8);
          onChange(dataUrl);
        };
        img.src = ev.target?.result as string;
      };
      reader.readAsDataURL(file);
    }
  };

  const isAutoGenerated = !value || value.includes('api.dicebear.com');

  return (
    <div className="space-y-2">
      <label className="block text-[11px] font-black text-slate-400 uppercase tracking-widest px-1">
        {label}
      </label>
      
      <div 
        className={`relative aspect-video w-full rounded-2xl bg-slate-50 dark:bg-gray-800 border-2 border-dashed border-slate-200 dark:border-gray-700 overflow-hidden group transition-all ${
          isUploading 
            ? 'cursor-not-allowed opacity-80' 
            : 'cursor-pointer hover:border-primary/50'
        }`}
        onClick={() => !isUploading && fileInputRef.current?.click()}
      >
        {isUploading && (
          <div className="absolute inset-0 z-20 bg-slate-950/60 backdrop-blur-xs flex flex-col items-center justify-center text-white gap-2 transition-all">
            <span className="animate-spin material-symbols-outlined text-[32px] text-primary">progress_activity</span>
            <span className="text-[10px] font-black uppercase tracking-widest text-slate-200">Đang tải lên DB...</span>
          </div>
        )}

        {value ? (
          <>
            <img 
              src={value} 
              alt="Thumbnail preview" 
              className="w-full h-full object-cover"
            />
            {!isUploading && (
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3">
                <div className="size-10 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center text-white">
                  <span className="material-symbols-outlined text-[20px]">edit</span>
                </div>
                {!isAutoGenerated && (
                  <button 
                    onClick={(e) => {
                      e.stopPropagation();
                      onChange(null); // This will trigger regeneration on save
                    }}
                    className="size-10 bg-red-500/80 backdrop-blur-md rounded-full flex items-center justify-center text-white hover:bg-red-600 transition-colors"
                    title="Gỡ bỏ ảnh tùy chỉnh"
                  >
                    <span className="material-symbols-outlined text-[20px]">delete</span>
                  </button>
                )}
              </div>
            )}
          </>
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-400 gap-2">
            <span className="material-symbols-outlined text-[40px]">add_photo_alternate</span>
            <span className="text-[10px] font-bold uppercase tracking-widest">Tải lên ảnh 16:9</span>
          </div>
        )}
        
        <input 
          type="file" 
          ref={fileInputRef}
          onChange={handleFileChange}
          accept="image/*"
          className="hidden"
          disabled={isUploading}
        />
      </div>
      
      {isAutoGenerated && value && (
        <p className="text-[10px] text-slate-400 italic px-1">
          * Đang sử dụng ảnh tự động. Tải ảnh lên để thay thế.
        </p>
      )}
    </div>
  );
}
